<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
$I->amOnPage('/');
$I->click('.header-sign__auth._action',"регистрация");
$I->click('.b-popup-register__type-private');
$I->waitForElement('b-modal__window', 5);
$I->fillField('#user-name',"Фродо");
$I->fillField('#user-passport',"Бэгинс");
$I->fillField('#user-email',"b.bagind@shire.com");
$I->fillField('#user-pass',"ring");
$I->fillField('#user-pass-repeat',"ring");
$I->fillField('#user-tel',"2020327");
$I->click('.register_button.register_button.js-submitBtn');
$I->waitForElement('b-modal__window', 5);
$I->dontSee('.b-modal__window');
$I->see("Фродо",'.header-sign__login');
$I->click('.header-sign__login');
$I->click('.login-nav__link');
$I->see('input.user-info__field-name[value="Фродо"]');
$I->see('input.user-info__field-email[value="b.bagind@shire.com"]');
$I->see("Ваши работы",'.user__switch _switch-active');
$I->see("Сохранить",'save_button js-submitBtn');
$I->seeInCurrentUrl('http://test.lama.by.dev.lovata.com/user/update/78');